### PR TITLE
spec: try using quiet logger

### PR DESCRIPTION
**Pull request by ivanoblomov**
Closes: n/a

# Goal
Try using quiet logger.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Oh, I meant: the spec_helper before hook could do the same "if you instantiate a Logger, you get a quiet instance back".

**Comment by ivanoblomov** [comment]
Not sure I follow. Could you show me what you mean in this branch?

**Comment by olleolleolle** [comment]
bild

Seems to work.

**Comment by olleolleolle** [comment]
@ivanoblomov Hope this helps!

**Comment by olleolleolle** [comment]
Thanks for taking this all the way!

**Pull request closed without merging**
