### PR TITLE
conf: reduce gem size

### PR DESCRIPTION
**Pull request by ivanoblomov**
# Closes: #140

## Goal
Reduce gem's size.

## Approach
1. Exclude all files from gem except source.
2. Retract `version.rb` (and use gemspec instead).
3. Remove enclosing folder `lib/google_maps_geocoder`, which makes explicit requires unnecessary.
4. Update RDoc's `.document`, misc. text files with 3.
5. Test locally before merging (by building and installing gem manually).

### Related: #73, #79, #80

Signed-off-by: Roderick Monje <rod@foveacentral.com>

### CODE REVIEW

**Comment by olleolleolle** [comment]
Is there a compelling reason _not_ to have a `lib/google_maps_geocoder.rb` and a `lib/google_maps_geocoder/*.rb` set of files?

**Comment by ivanoblomov** [comment]
Good call. Vaguely recall a namespacing issue that required it, but let's revisit.

**Comment by ivanoblomov** [comment]
Got rid of the version file too, so we got a net reduction of nine lines. No idea what that old namespace issue was.

**Comment by ivanoblomov** [comment]
This is read for review too.

**Review by olleolleolle — APPROVED** [review]
This seems simpler, let's go with that!

**Pull request merged**
