### PR TITLE
CI: run CI on PRs only

### PR DESCRIPTION
**Pull request by ivanoblomov**
Closes: n/a

# Goal
Run CI on PRs only instead of pushes so fork PRs can be tested too, but without this redundancy:

duplicate-checks

# Approach
(self-explanatory)

Signed-off-by: Roderick Monje <rod@foveacentral.com>

### CODE REVIEW

**Comment by olleolleolle** [comment]
This leaves the people who offer PRs without a run. This happened to me.

**Comment by ivanoblomov** [comment]
@olleolleolle ah, you mean on forks?

**Comment by ivanoblomov** [comment]
Since [secrets are not passed to workflows that are triggered by a pull request from a fork](https://github.com/organizations/FoveaCentral/settings/secrets/actions) anyway, looks like the best solution here is to:

1. port the secrets from the repo to the organization
2. then run CI on `push` only because of the [Code Climate bug with PR runs](https://github.com/aktions/codeclimate-test-reporter/issues/17) I found trying to address #87.

**Comment by ivanoblomov** [comment]
Closing in favor of #88.

**Comment by ivanoblomov** [comment]
@olleolleolle I moved `GOOGLE_MAPS_API_KEY` to the `FoveaCentral` organization, but not the others (`CC_TEST_REPORTER_ID` and `RUBYGEMS_AUTH_TOKEN`) since they're repo-specific.

Because org/repo secrets can't be shared across organizations, there's no obvious way to get fork PRs to pass regardless of what workflow event you use. For this reason, I'm reverting CI to `push`.

If there's a good reason to run CI on pull requests instead, however, I have a workaround ready in #90, but note it *skips test coverage entirely* because there's an [incompatibility with `after-build` and `pull_request` events](https://github.com/marketplace/actions/setup-code-climate), possibly having to do with [differences in `ref`s and `SHA`s](https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-does-pull_request-affect-actionscheckout). 🤷

**Pull request closed without merging**
